controllers:
    resource: ../src/Controller/
    type: attribute
delete_prize:
    path: '/prize/delete/{prizeId}'
    controller: App\Controller\GiveawayController::deletePrize
download_data:
    path: /download-data
    controller: App\Controller\DownloadController::downloadData

